import { ThemeProvider } from "next-themes";
import localFont from "next/font/local";
import { cn } from "@/utils";
import type { Metadata } from "next";
import "@/styles/globals.css";

// Font files can be colocated inside of `app`
const GilroyFont = localFont({
  src: [
    {
      path: "../assets/fonts/gilroy.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/gilroy-bold.otf",
      weight: "800",
      style: "normal",
    },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Klot Ecommerce by luisfalconmx",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scroll-smooth" lang="en" suppressHydrationWarning>
      <body
        className={cn(
          GilroyFont.className,
          "text-black dark:bg-dark-100 dark:text-white"
        )}
      >
        <ThemeProvider defaultTheme="dark" attribute="data-theme">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
